const playbook=[
{keys:["already have","happy with","current provider","have internet"],tag:"Discovery opportunity",q:"What do you like most about your current internet service?",why:"You're not fighting the customer's current provider. You're opening discovery and looking for price, reliability, speed, or service gaps.",signal:"They mention a pain point, price, outages, slow speeds, fees, or something they'd change.",transition:"If you could improve that one thing without making the overall experience worse, would you be open to comparing the options?",push:"What would have to be different for switching to actually be worth considering?",obj:"Find one measurable pain point and quantify it."},
{keys:["price","expensive","cost","high"],tag:"Price discovery",q:"What are you currently paying each month for your service?",why:"Understand the customer's baseline before defending price. A specific number gives you something to compare.",signal:"They reveal their bill, fees, or frustration with what they receive for the price.",transition:"If I could show you a comparable option at a better overall value, would you want to see the difference?",push:"Besides monthly price, what matters most to you when choosing your internet service?",obj:"Quantify the current bill, then connect value to their priority."},
{keys:["think","consider","talk to","later"],tag:"Hidden objection",q:"Absolutely. What part would you like to think over the most?",why:"'Think about it' is often a placeholder for a concern. Find the specific issue without creating pressure.",signal:"They name a specific concern such as price, reliability, contract, installation, or timing.",transition:"If we could clear that concern up, would you feel comfortable making a decision today?",push:"Is there anything else that would keep you from moving forward?",obj:"Identify the real unresolved concern."},
{keys:["don't need","dont need","another bill","need it"],tag:"Needs discovery",q:"What are you currently using for internet at home?",why:"You can't establish need until you understand the customer's current setup and how it fits the household.",signal:"They reveal multiple users, streaming, gaming, work-from-home needs, reliability issues, or an expensive setup.",transition:"How well does that setup handle everything your household needs today?",push:"If it's working well, what would you want to improve about it, if anything?",obj:"Understand current usage and uncover a gap."}
];
function coach(text){let t=text.toLowerCase();let p=playbook.find(x=>x.keys.some(k=>t.includes(k)))||{tag:"Discovery opportunity",q:"What is the biggest reason you feel that way?",why:"Uncover the reason behind the objection before presenting a pitch. Their answer gives you the next direction.",signal:"They explain a specific concern, need, or desired outcome.",transition:"If we could address that concern, would you be open to looking at an option that fits what you need?",push:"What would need to be different for this to make sense for you?",obj:"Uncover the real objection before presenting a solution."};return p}
const $=id=>document.getElementById(id);
function showCoach(){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active-view"));$("coach").classList.add("active-view");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view==="coach"))}
function run(){let text=$("input").value.trim();if(!text){toast("Enter a customer statement first.");return}let p=coach(text);$("empty").classList.add("hidden");$("output").classList.remove("hidden");$("title").textContent=text.length>90?text.slice(0,90)+"…":text;$("tag").textContent=p.tag;$("question").textContent=p.q;$("why").textContent=p.why;$("signal").textContent=p.signal;$("transition").textContent=p.transition;$("pushback").textContent=p.push;$("objective").textContent=p.obj}
function toast(msg){$("toast").textContent=msg;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",1800)}
$("coachBtn").onclick=run;
$("randomBtn").onclick=()=>{$("input").value=["I already have internet and I'm happy with it.","Your price is too high.","I need to think about it.","I don't need another bill."][Math.floor(Math.random()*4)];run()};
document.querySelectorAll("[data-example]").forEach(b=>b.onclick=()=>{$("input").value=b.dataset.example;run()});
document.querySelectorAll(".copy").forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText($(b.dataset.id).textContent);b.textContent="Copied";setTimeout(()=>b.textContent="Copy",900)});
$("saveBtn").onclick=()=>{let item={text:$("input").value,tag:$("tag").textContent,date:new Date().toLocaleDateString(),score:Math.floor(76+Math.random()*20)};let h=JSON.parse(localStorage.getItem("cc_history")||"[]");h.unshift(item);localStorage.setItem("cc_history",JSON.stringify(h.slice(0,25)));renderHistory();toast("Conversation saved.")};
function renderHistory(){let h=JSON.parse(localStorage.getItem("cc_history")||"[]");$("historyRows").innerHTML=(h.length?h:[{text:"I already have internet and I'm happy with it.",tag:"Discovery opportunity",date:"Demo",score:84},{text:"Your price is too high.",tag:"Price discovery",date:"Demo",score:88}]).map(x=>`<div class="row"><span>${x.text}</span><span>${x.tag}</span><span>${x.date}</span><span class="score">${x.score}</span></div>`).join("")}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{let v=b.dataset.view;document.querySelectorAll(".view").forEach(x=>x.classList.remove("active-view"));$(v).classList.add("active-view");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(v==="history")renderHistory()});
document.querySelectorAll("[data-plan]").forEach(b=>b.onclick=()=>{$("billingMsg").classList.remove("hidden");$("billingMsg").textContent=`Demo checkout selected: ${b.dataset.plan}. Connect this button to a Stripe Checkout Session on your server for a real subscription.`});
renderHistory();
